### PR TITLE
Have 8 SG rounds before restart

### PR DESCRIPTION
**Pull request by IcedCode**
For servers SG01, SG02 & SG03

Been playing a bit of SG today and I've asked people on the server and multiple SG rounds is something we would really like to see. As it's really annoying having to switch servers all the time after every single game and people will be likely to play more of it and the amount of people playing will be higher as the server can build up over a longer period of time instead of just 60 seconds, therefore making games better and more varied

### CODE REVIEW

**Comment by steven5703** [comment]
@KyloCode Would something like this even work?

**Comment by Tanpiku** [comment]
I'd much prefer a maximum of 4, as survival games maps are large and cause a lot of load on servers. A nebula map may have 4 to 5 region files

**Comment by steven5703** [comment]
@KyloCode Would something like this even work?

**Comment by IcedCode** [comment]
@steven5703  Yes look at Arcade01

**Comment by IcedCode** [comment]
@Tanpiku I agree else it would become a bit laggy or crash the server or something.

**Comment by Tanpiku** [comment]
You open a PR to have 4 rounds if you want!

**Pull request closed without merging**
